# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Blog.create([
  { :user_id => 1, :title => "test1", :body => "test1", :created_at => "2011-10-06 11:51:44", :updated_at => "2011-10-06 11:51:44" },
  { :user_id => 1, :title => "test2", :body => "test2", :created_at => "2011-10-06 11:51:50", :updated_at => "2011-10-06 11:51:50" }
])



User.create([
  { :name => "test1", :created_at => "2011-10-06 11:51:23", :updated_at => "2011-10-06 11:51:23" }
])


